services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Typo3OnAws\AwsCloudfront\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Typo3OnAws\AwsCloudfront\Ajax\AjaxController:
    public: true;

  Typo3OnAws\AwsCloudfront\Hook\ButtonBarHook:
    public: true;

#  Typo3OnAws\AwsCloudfront\EventListener\ExampleListener:
#    tags:
#      - name: event.listener
#        identifier: 'cloudfrontInvalidationExampleListener'
#        event: Typo3OnAws\AwsCloudfront\EventDispatcher\CloudfrontInvalidationRequestEvent
#        before: 'cloudfrontInvalidationDatabaseListener'

  Typo3OnAws\AwsCloudfront\EventListener\DatabaseListener:
    tags:
      - name: event.listener
        identifier: 'cloudfrontInvalidationDatabaseListener'
        event: Typo3OnAws\AwsCloudfront\EventDispatcher\CloudfrontInvalidationRequestEvent
