services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Typo3OnAws\AwsCloudfront\:
    resource: '../Classes/*'

  Typo3OnAws\AwsCloudfront\Ajax\AjaxController:
    public: true;

  Typo3OnAws\AwsCloudfront\Hook\ButtonBarHook:
    public: true;

  Typo3OnAws\AwsCloudfront\Utility\AwsExceptionHandler:
    public: true;
